docker load -i spin-images/mc.tar
docker load -i spin-images/forwarder-controller.tar
docker load -i spin-images/forwarder-agent.tar
docker load -i spin-images/ubi8-gate.tar
docker load -i spin-images/ubi8-oes-dashboard.tar
docker load -i spin-images/ubi8-oes-db.tar
docker load -i spin-images/ubi8-oes-platform.tar
docker load -i spin-images/ubi8-oes-sapor.tar
docker load -i spin-images/ubi8-oes-ui.tar
docker load -i spin-images/ubi8-oes-autopilot.tar
docker load -i spin-images/ubi8-oes-visibility.tar
