docker tag quay.io/opsmxpublic/ubi8-oes-deck:3.5.1 docker.io/ksrinimba/ubi8-oes-deck:3.5.1
docker tag quay.io/opsmxpublic/ubi8-oes-front50:0.27.1 docker.io/ksrinimba/ubi8-oes-front50:0.27.1
docker tag quay.io/opsmxpublic/ubi8-oes-orca:2.20.3 docker.io/ksrinimba/ubi8-oes-orca:2.20.3
docker tag quay.io/opsmxpublic/ubi8-oes-spin-gate:1.22.1 docker.io/ksrinimba/ubi8-oes-spin-gate:1.22.1
docker tag quay.io/opsmxpublic/ubi8-spin-clouddriver:8.0.4 docker.io/ksrinimba/ubi8-spin-clouddriver:8.0.4
docker tag quay.io/opsmxpublic/ubi8-spin-echo:2.17.1 docker.io/ksrinimba/ubi8-spin-echo:2.17.1
docker tag quay.io/opsmxpublic/ubi8-spin-fiat:1.16.0 docker.io/ksrinimba/ubi8-spin-fiat:1.16.0
docker tag quay.io/opsmxpublic/ubi8-spin-igor:1.16.0 docker.io/ksrinimba/ubi8-spin-igor:1.16.0
docker tag quay.io/opsmxpublic/ubi8-spin-kayenta:0.21.0 docker.io/ksrinimba/ubi8-spin-kayenta:0.21.0
docker tag quay.io/opsmxpublic/ubi8-spin-rosco:0.25.0 docker.io/ksrinimba/ubi8-spin-rosco:0.25.0
docker tag quay.io/opsmxpublic/ubi8-gate:v3.9.0 docker.io/ksrinimba/ubi8-gate:v3.9.0
docker tag quay.io/opsmxpublic/ubi8-oes-autopilot:v3.9.0 docker.io/ksrinimba/ubi8-oes-autopilot:v3.9.0
docker tag quay.io/opsmxpublic/ubi8-oes-dashboard:v3.9.0 docker.io/ksrinimba/ubi8-oes-dashboard:v3.9.0
docker tag quay.io/opsmxpublic/ubi8-oes-db:v2.0.0 docker.io/ksrinimba/ubi8-oes-db:v2.0.0
docker tag quay.io/opsmxpublic/ubi8-oes-deck:3.5.1 docker.io/ksrinimba/ubi8-oes-deck:3.5.1
docker tag quay.io/opsmxpublic/ubi8-oes-platform:v3.9.0 docker.io/ksrinimba/ubi8-oes-platform:v3.9.0
docker tag quay.io/opsmxpublic/ubi8-oes-sapor:v3.9.0 docker.io/ksrinimba/ubi8-oes-sapor:v3.9.0
docker tag quay.io/opsmxpublic/ubi8-oes-ui:v3.9.0 docker.io/ksrinimba/ubi8-oes-ui:v3.9.0
docker tag quay.io/opsmxpublic/ubi8-oes-visibility:v3.9.0 docker.io/ksrinimba/ubi8-oes-visibility:v3.9.0
docker tag quay.io/opsmxpublic/oes-pre-configure:v2 docker.io/ksrinimba/oes-pre-configure:v2
docker tag quay.io/opsmxpublic/create-secret:v10 docker.io/ksrinimba/create-secret:v10
docker tag quay.io/opsmxpublic/awsgit:v2 docker.io/ksrinimba/awsgit:v2
docker tag quay.io/opsmxpublic/k8s-decoder:hal docker.io/ksrinimba/k8s-decoder:hal
docker tag quay.io/opsmxpublic/spin-sample-pipeline:1.0 docker.io/ksrinimba/spin-sample-pipeline:1.0
docker tag postgres:9.6.5 docker.io/ksrinimba/postgres:9.6.5
docker tag bitnami/kubectl:1.18.5 docker.io/ksrinimba/kubectl:1.18.5
docker tag busybox:1.28 docker.io/ksrinimba/busybox:1.28
docker tag opsmxdev/pipepromot:1.0 docker.io/ksrinimba/pipepromot:1.0
docker tag quay.io/opsmxpublic/opsmx-custom-binaries:vault-k8s-cli docker.io/ksrinimba/opsmx-custom-binaries:vault-k8s-cli
docker tag docker.io/osixia/openldap:1.2.4 docker.io/ksrinimba/openldap:1.2.4
