wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/awsgit.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/busybox.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/create-secret.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/k8s-decoder.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/kubectl.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/oes-pre-configure.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/openldap.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/opsmx-custom-binaries.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/pipepromot.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/postgres.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/spin-sample-pipeline.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/ubi8-gate.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/ubi8-oes-autopilot.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/ubi8-oes-dashboard.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/ubi8-oes-db.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/ubi8-oes-deck.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/ubi8-oes-front50.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/ubi8-oes-orca.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/ubi8-oes-platform.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/ubi8-oes-sapor.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/ubi8-oes-spin-gate.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/ubi8-oes-ui.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/ubi8-oes-visibility.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/ubi8-spin-clouddriver.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/ubi8-spin-echo.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/ubi8-spin-fiat.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/ubi8-spin-igor.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/ubi8-spin-kayenta.tar
wget https://opsmx-transit.s3.us-west-2.amazonaws.com/airgap-aug18/ubi8-spin-rosco.tar
