docker push docker.io/ksrinimba/ubi8-oes-deck:3.5.1
docker push docker.io/ksrinimba/ubi8-oes-front50:0.27.1
docker push docker.io/ksrinimba/ubi8-oes-orca:2.20.3
docker push docker.io/ksrinimba/ubi8-oes-spin-gate:1.22.1
docker push docker.io/ksrinimba/ubi8-spin-clouddriver:8.0.4
docker push docker.io/ksrinimba/ubi8-spin-echo:2.17.1
docker push docker.io/ksrinimba/ubi8-spin-fiat:1.16.0
docker push docker.io/ksrinimba/ubi8-spin-igor:1.16.0
docker push docker.io/ksrinimba/ubi8-spin-kayenta:0.21.0
docker push docker.io/ksrinimba/ubi8-spin-rosco:0.25.0
docker push docker.io/ksrinimba/ubi8-gate:v3.9.0
docker push docker.io/ksrinimba/ubi8-oes-autopilot:v3.9.0
docker push docker.io/ksrinimba/ubi8-oes-dashboard:v3.9.0
docker push docker.io/ksrinimba/ubi8-oes-db:v2.0.0
docker push docker.io/ksrinimba/ubi8-oes-deck:3.5.1
docker push docker.io/ksrinimba/ubi8-oes-platform:v3.9.0
docker push docker.io/ksrinimba/ubi8-oes-sapor:v3.9.0
docker push docker.io/ksrinimba/ubi8-oes-ui:v3.9.0
docker push docker.io/ksrinimba/ubi8-oes-visibility:v3.9.0
docker push docker.io/ksrinimba/oes-pre-configure:v2
docker push docker.io/ksrinimba/create-secret:v10
docker push docker.io/ksrinimba/awsgit:v2
docker push docker.io/ksrinimba/k8s-decoder:hal
docker push docker.io/ksrinimba/spin-sample-pipeline:1.0
docker push docker.io/ksrinimba/postgres:9.6.5
docker push docker.io/ksrinimba/kubectl:1.18.5
docker push docker.io/ksrinimba/busybox:1.28
docker push docker.io/ksrinimba/pipepromot:1.0
docker push docker.io/ksrinimba/opsmx-custom-binaries:vault-k8s-cli
docker push docker.io/ksrinimba/openldap:1.2.4
