docker load -i awsgit.tar
docker load -i busybox.tar
docker load -i create-secret.tar
docker load -i k8s-decoder.tar
docker load -i kubectl.tar
docker load -i oes-pre-configure.tar
docker load -i openldap.tar
docker load -i opsmx-custom-binaries.tar
docker load -i pipepromot.tar
docker load -i postgres.tar
docker load -i spin-sample-pipeline.tar
docker load -i ubi8-gate.tar
docker load -i ubi8-oes-autopilot.tar
docker load -i ubi8-oes-dashboard.tar
docker load -i ubi8-oes-db.tar
docker load -i ubi8-oes-deck.tar
docker load -i ubi8-oes-front50.tar
docker load -i ubi8-oes-orca.tar
docker load -i ubi8-oes-platform.tar
docker load -i ubi8-oes-sapor.tar
docker load -i ubi8-oes-spin-gate.tar
docker load -i ubi8-oes-ui.tar
docker load -i ubi8-oes-visibility.tar
docker load -i ubi8-spin-clouddriver.tar
docker load -i ubi8-spin-echo.tar
docker load -i ubi8-spin-fiat.tar
docker load -i ubi8-spin-igor.tar
docker load -i ubi8-spin-kayenta.tar
docker load -i ubi8-spin-rosco.tar
